CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
username TEXT NOT NULL, 
hash TEXT NOT NULL,
amount_invested NUMERIC NOT NULL DEFAULT 0,
value_of_assets NUMERIC NOT NULL DEFAULT 0, 
cash NUMERIC NOT NULL DEFAULT 10000.00,
value_of_portfolio NUMERIC NOT NULL DEFAULT 10000.00);

CREATE UNIQUE INDEX username ON users (username);

CREATE TABLE stocks (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
symbol TEXT NOT NULL,
open_price NUMERIC NOT NULL,
current_price NUMERIC NOT NULL,
increase NUMERIC NOT NULL);

CREATE UNIQUE INDEX symbol on stocks (symbol);

CREATE TABLE holdings (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
user_id INTEGER NOT NULL, 
symbol INTEGER NOT NULL,
shares INTEGER NOT NULL,
total_value NUMERIC NOT NULL,
FOREIGN KEY (user_id) REFERENCES users (id));

CREATE TABLE transactions (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
user_id INTEGER NOT NULL,
symbol TEXT NOT NULL,
shares INTEGER NOT NULL,
value NUMERIC NOT NULL,
datetime TEXT NOT NULL,
type TEXT NOT NULL,
FOREIGN KEY (user_id) REFERENCES users (id));

